export const actionTypes = {
    SET_PRODUCTS: "SET_PRODUCTS",
    REMOVE_PRODUCTS: "REMOVE_PRODUCTS",
    SELECTED_PRODUCTS: "SELECTED_PRODUCTS",
    ADD_TO_CART: "ADD_TO_CART",
    REMOVE_SELECTED_PRODUCTS: "REMOVE_SELECTED_PRODUCTS",
    SET_CATEGORIES: "SET_CATEGORIES"
}