export const actionTypes = {
    SET_PRODUCTS: "SET_PRODUCTS",
    SET_TAB : "SET_TAB",
    REMOVE_PRODUCTS: "REMOVE_PRODUCTS",
    SELECTED_PRODUCTS: "SELECTED_PRODUCTS",
    ADD_TO_CART: "ADD_TO_CART",
    UPDATE_CART_ITEMS: "UPDATE_CART_ITEMS",
    REMOVE_SELECTED_PRODUCTS: "REMOVE_SELECTED_PRODUCTS",
    SET_CATEGORIES: "SET_CATEGORIES"
}